### PR TITLE
Add notes for fixes which will be part of Linux 5.3

### PR DESCRIPTION
**Pull request by christophgysin**

### CODE REVIEW

**Comment by Dunedan** [comment]
Thanks for this PR, but as 5.3 isn't released yet it'll have to wait to get merged until it is. :slightly_smiling_face:

**Comment by christophgysin** [comment]
No problem. It's part of 5.3-rc1, so I got excited :)

Feel free to leave it hanging here until 5.3 is out.

**Comment by Fuzen-py** [comment]
> No problem. It's part of 5.3-rc1, so I got excited :)
> 
> Feel free to leave it hanging here until 5.3 is out.

Didn't notice this change, also excited for this. One step closer to having an arch install on my mbp

**Comment by decorumos** [comment]
*bump*
tested with final 5.3 release on eoan this morning
this PR should likely be included now :)

**Comment by Dunedan** [comment]
Thanks again for this pull request. :+1:

**Pull request merged**
