### PR TITLE
Updated status of T2 MacBooks

### PR DESCRIPTION
**Pull request by Redecorating**
* Added note in introduction about T2 Macs
* Added missing t2 models
* Audio partially working for all t2 models, input can be unstable
* Camera working on all T2 Models, with apple-bce and linux-mbp kernel
  patches.
* iGPU working on 15,1 and 16,1, but it does break resume.
* 16,1 no longer needs RC kernel for amdgpu driver.
* apple-bce is maintained on a different repo
* Trackpads on T2 macs have deadzones
* 16,* no keyboard backlight
* Linked to patch in linux-mbp-arch that fixes iGPU overscan
* T2 Macs need apple-ib-tb unloaded before suspend
* T2 Macs need applesmc patches from linux-mbp, and a different fork of
  mbpfan
* WiFi works for all t2 models except 15,4 and 16,3 (16,3 should work
  but isn't tested)
* In a few places, I've linked to https://wiki.t2linux.org for T2
  specific instructions.

### CODE REVIEW

**Comment by Dunedan** [comment]
@Redecorating: First of all: Thank you so much for this comprehensive PR. Your effort is very much appreciated. :+1:

I've been torn apart how to continue with this PR. That's because to me it feels like its mainly referencing another collection of notes, instead of documenting the actual steps necessary. For example it refers to the collection of patches one needs to have (https://github.com/aunali1/linux-mbp-arch), instead of listing the individual patches necessary for the individual components. While my first reaction was to request changing that, I'm not sure anymore if that's a viable idea, given the number of patches necessary.

Another option I could think of would be to remove the information for the T2 based MacBook Pro models from this repository and just add a prominent link pointing to https://wiki.t2linux.org/. That doesn't feel like the right way to proceed for me either, as `t2linux` seems to have a different goal than this repository. Back in 2017 I created this repository for two reasons: Provide a quick overview of the Linux support for the different MacBook Pro models and provide a central source for discussions around the reverse engineering of the hardware and coordinating upstreaming of the necessary quirks and drivers for it. Please correct me if I'm wrong, but `t2linux` seems to have a different, probably more user centric, approach, by providing detailed Linux distribution specific installation instructions and just collecting patches without trying to upstream them.

While looking at the `t2linux` wiki I was shocked to learn how many patches are there for the T2 based MacBook Pro models and that I couldn't find any progress about upstreaming them. Did I just miss that or is there actually nobody working on upstreaming these patches?

I believe the goal of a resource like this repository should be to be redundant eventually when all quirks and drivers for all components are upstreamed and just work out of the box.

So I'm not sure how to proceed here, but I'd be happy to hear other opinions.

**Comment by seamusdemora** [comment]
@Dunedan: FWIW, I think your rationale for this repo is completely sound, and that "upstreaming" the information here is a sound and useful idea. As you've said, the `t2linux` site has a different orientation - perhaps as you describe it, _"more user-centric"_. Personally, I feel there is a need for both, and hope you decide to continue this effort. 

By way of perspective: As a Mac user, I have absolutely no interest in following Apple's disingenuous software "development". Perhaps I should be classified as a former Mac user as I will not "upgrade" beyond Catalina - which is also awful, but came pre-installed. Nevertheless, I still believe Apple's hardware is very good. I've converted my old 2011 MBP to dual-boot Ubuntu/High Sierra. I've got two other later-model MBPs that would have Linux on them if I felt it was stable & usable. I have friends and acquaintances who feel the same way. They see Linux running smartly on my 10-year-old MBP, and express regret that they let go of their "old" hardware.  

This post is only a note of encouragement - encouragement to continue your efforts in some capacity.

**Comment by marc-git** [comment]
> So I'm not sure how to proceed here, but I'd be happy to hear other opinions.

I don't have an opinion but I think it's worth commending you on your attitude here. Exemplary OSS inclusive non-authoritarian leadership.

**Comment by networkException** [comment]
The t2linux wiki was created to be able to help people with getting linux running on their t2 macs, a task that was previously done mainly by the people on a discord needing to remeber all aspects of the installation themselves. So calling it user centric is completly valid. This repository is intentionally linked on top of the guides on our index page, as you already pointed out it provides a more technical view on the matter.

**Comment by Redecorating** [comment]
I've had a go at rewriting each section to not depend on the t2wiki and be more technical, [here](https://gist.github.com/Redecorating/471f35ad2ac1d6e6d169527b292619f0). I still need to rewrite the WiFi bit. If this is a better way of doing it, I can add a commit to this pr changing it to what's in that gist. There are still quite a few patches mentioned, so that might still be an issue.

With upstreaming the patches, I know @aunali1 has done work on making the patches upstreamable, but I don't know when they'll be submitted upstream (if they haven't already), or if they are in their finalised state.

The t2 wiki is more user centric and this is more technical, that's a good way of looking at it.

**Comment by Redecorating** [comment]
The changes made in this PR have become quite outdated. Some of the patches have made their way upstream, wifi is all working with patches from asahilinux, etc etc.

**Pull request closed without merging**
