### PR TITLE
kernels >= 4.11 include NVMe patch

### PR DESCRIPTION
**Pull request by tudorbarascu**
@Dunedan Thanks a lot for pushing the patch into mainline.
Many thanks for your MacBook work also!

### CODE REVIEW

**Comment by Dunedan** [comment]
I was planning to adjust the documentation as soon as 4.11 gets officially released, but your contribution is welcome as well. :smile:

If you don't mind I'd like to see some changes:
- The summary table at the top of the documentation still states that an out-of-tree patch is needed, which isn't the case anymore with 4.11, so this should be removed.
- I'd like to keep the documentation as short as possible for all components which just work, so the link to the commit isn't really necessary.
- You could also move the commit regarding 4.11 to the top of the NVMe paragraph as that it just works will be the default and everything else is just a fall-back for older kernel versions.

**Comment by tudorbarascu** [comment]
Should be good now!
I'm not familiar with kernel development, do you think making a cherry-pick on the 4.9 branch (which is LTS) would get approved?
It would certainly be nice!
Thanks again for your contribution.
If you think I can help with anything please say so.
It would be nice if we could find someone that can fix the remaining issues (paid of course).

**Comment by Dunedan** [comment]
> I'm not familiar with kernel development, do you think making a cherry-pick on the 4.9 branch (which is LTS) would get approved?

Sorry, no idea. The patch for NVMe was my first kernel contribution as well. There should be documentation somewhere what qualifies for inclusion into an LTS kernel.

Aside from that I don't know if it does make sense to backport such features, as it's just one of many components which would work. Others would still require patches.

> If you think I can help with anything please say so.

There is lots of stuff to help with. Just pick a component which isn't working yet and get it to work. :wink:
I don't know your background, but if you're familiar with C, improving the keyboard & touchpad driver (https://github.com/cb22/macbook12-spi-driver/) and finally getting it upstream would be really cool as these are core components which would be very valuable working out of the box to attract more users.

Other tasks which do not require programming and come to my mind right now are:
- use Windows to gather the SPI-commands used for touchpad initialization, so @roadrunner2 can adjust the driver to fix the initialization issues of the touchpad (https://github.com/cb22/macbook12-spi-driver/issues/6)
- Somehow get in contact with Broadcom, so they'll have a look if the wifi issues are firmware related and they're able to fix them, so we finally have properly working wifi (https://bugzilla.kernel.org/show_bug.cgi?id=193121)

**Comment by tudorbarascu** [comment]
I have just begun learning C so probably I won't be much of use here.
I have the 13,1 model (no touchbar). I can gather the SPI-commands from Windows for sure.
What I can surely do is to gather some funds to spend if someone is willing to work on one of the remaining issues. Unfortunately I don't know anyone that's up to it. Do you?

**Comment by Dunedan** [comment]
> I have the 13,1 model (no touchbar).

That's great. Would you be so kind to provide the output of `dmesg`, `lspci -v` and `lsusb -v`? I'm interested in learning how they drive the webcam on these models. Does your webcam work out of the box or do you need the quirk from the instructions?

> What I can surely do is to gather some funds to spend if someone is willing to work on one of the remaining issues. Unfortunately I don't know anyone that's up to it. Do you?

There is already an unclaimed bounty for the keyboard & touchpad driver (https://www.bountysource.com/issues/35422234-macbook8-1-12-inch-early-2015-keyboard-and-trackpad-don-t-work) you're obviously already aware of. :smile:

I also don't know anybody who's up to do some funded work on further support. I'll for myself do what I can, but my knowledge about C and all the involved Linux subsystems is also pretty limited, so I'm not the right addressee for it.

**Comment by tudorbarascu** [comment]
Heres' a zip file with the output from ``dmesg``, ``lspci -v`` and ``lsusb -v``:
https://www.dropbox.com/s/h4t1yc2suzlax7q/output_13.1.zip?dl=0

The webcam doesn't work out of the box + I haven't tested the instructions to make it work.
On the priorities list for me: 
- Keyboard + trackpad
- storage
- sleep

**Comment by Dunedan** [comment]
> Heres' a zip file with the output from dmesg, lspci -v and lsusb -v:

Thanks a lot, but it appears not to contain the output of `lspci -v`, but instead the output of `lsusb -v` twice. If you could provide the output of `lspci -v` as well, that'd be awesome.

> On the priorities list for me:
>    Keyboard + trackpad
>    storage
>    sleep
- For keyboard and trackpad https://github.com/cb22/macbook12-spi-driver is the best location for all related discussion.
- Storage should just work. I've some problems that my MBP doesn't boot properly each time, which could be related to NVMe, but I'm not sure about that yet. As suggested in another issue (https://github.com/Dunedan/mbp-2016-linux/issues/1#issuecomment-290918392) the problems with sleep could be related to a missing vendor specific command for shutting down the NVMe controller.

That'd be the next steps for these components from my point of view.

**Comment by tudorbarascu** [comment]
Thanks for the info, I've recreated the zip file to include the correct lspci output  (must have been daydreaming at the moment). The link in my previous comment points to the recreated zip file.

All the best

**Pull request merged**
